version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"    # MinIO API Port
      - "9090:9090"    # MinIO Console Port
    volumes:
      - /mnt/data/content:/mnt/data
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "miniopassword"
    command: server --console-address ":9090" /data
    networks:
      - proxy
    restart: always

  mc:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin miniopassword;
      mc mb -p local/mybucket || true;
      tail -f /dev/null
      "
    networks:
      - proxy

volumes:
  minio-data:

networks:
  proxy:
    driver: bridge