services:
  reverse-proxy:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx_conf/proxy.conf:/etc/nginx/proxy.conf:rw
      - ./nginx_conf/conf.d:/etc/nginx/conf.d:rw
      - ./nginx_conf/ssl:/etc/nginx/ssl/:ro
      - ./nginx_conf/html:/usr/share/nginx/html
      - /var/log/nginx/:/var/log/nginx/:rw
    restart: always
    ports:
      - 443:443
      - 80:80

networks:
  default:
    name: proxy
    external: true